### ISSUE TITLE
IR Emitter does not work.

### ISSUE THREAD

**Issue by HubKing** [exynos5420/android_device_samsung_v1awifi#2]
I think the following hard-coded ranges are wrong. They are different from the values the stock ROM returned.

file: android_device_samsung_v1awifi/hal/consumerir/consumerir.c
static const consumerir_freq_range_t consumerir_freqs[] = {
    {.min = 30000, .max = 30000},
    {.min = 33000, .max = 33000},
    {.min = 36000, .max = 36000},
    {.min = 38000, .max = 38000},
    {.min = 40000, .max = 40000},
    {.min = 56000, .max = 56000},
};

**Comment by thompatry** [comment]
This has been resolved.
